pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Navigate to the complete/ directory and run Maven
                dir('complete') {
                    sh './mvnw clean package'
                }
            }
        }
        stage('Deploy') {
            steps {
                // Copy the JAR file to the deployment location
                dir('complete') {
                    sh 'sudo cp target/*.jar /var/www/html/app.jar'
                }
            }
        }
    }
}

